name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  windows-test:
    runs-on: windows-latest
    strategy:
      matrix:
        go_version: ["1.17.6", "1.16.5", "1.15.13"]
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go_version}}

    - name: Test
      run: go test -v -race ./...
  
  linux-test:
    runs-on: windows-latest
    strategy:
      matrix:
        go_version: ["1.17.6", "1.16.5", "1.15.13"]
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go_version}}

    - name: Test
      run: go test -v -race ./...
      
  macos-test:
    runs-on: windows-latest
    strategy:
      matrix:
        go_version: ["1.17.6", "1.16.5", "1.15.13"]
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go_version}}

    - name: Test
      run: go test -v -race ./...
