name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mutli-system-test:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest]
        go_version: ["1.17.6", "1.16.5", "1.15.13"]
    runs-on: ${{matrix.os}}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go_version}}
    - name: CheckOut Code
      uses: actions/checkout@v2
    - name: Test
      run:  go test -race -v ./.
