name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  windows-test:
    runs-on: windows-latest
    strategy:
      matrix:
        go-version: ["1.11.x","1.12.x","1.13.x","1.14.x","1.15.x","1.16.x","1.17.x"]
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go_version}}

    - name: Test
      run: go test -v -race ./...
  
  linux-test:
    runs-on: windows-latest
    strategy:
      matrix:
        go-version: ["1.11.x","1.12.x","1.13.x","1.14.x","1.15.x","1.16.x","1.17.x"]
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go_version}}

    - name: Test
      run: go test -v -race ./...
      
  macos-test:
    runs-on: windows-latest
    strategy:
      matrix:
        go-version: ["1.11.x","1.12.x","1.13.x","1.14.x","1.15.x","1.16.x","1.17.x"]
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go_version}}

    - name: Test
      run: go test -v -race ./...
